det_thresh : 0.1
max_age : 3
mal_thresh : 25   #distance threshold of first association, calculated by Mahalanobis Distance 
eu_thresh : 135   #distance threshold of first association, calculated by Euclidean Distance
sec_thresh : 150  #distance threshold of second association
is_velocity_const : False
use_orig_KF : False